### ISSUE TITLE
Mautic Gated Videos

### ISSUE THREAD

**Issue by Aneta09** [mautic/mautic-wordpress#43] opened 2017-04-24 21:31 UTC
Somebody have been tried this function? Does it work?

Mautic supports gated videos with Youtube, Vimeo, and MP4 as sources.

To load gated videos into your WP content, insert this shortcode where you'd like it to appear:

[mautic type="video" gate-time="#" form-id="#" src="URL"]
Replace the # signs with the appropriate number. For gate-time, enter the time (in seconds) where you want to pause the video and show the mautic form. For form-id, enter the id of the mautic form that you'd like to display as the gate. Replace URL with the browser URL to view the video. In the case of Youtube or Vimeo, you can simply use the URL as it appears in your address bar when viewing the video normally on the providing website. For MP4 videos, enter the full http URL to the MP4 file on the server.

**Comment by Aneta09** [comment] 2017-04-25 07:43
In my first case: Video starts, next it stops on time but form doesn't work. I have information: undefined.
Second: Video doesn't start, I see only video's frame. 

I am using two different themes for those sites. JS tracking works correctly.

What is wrong? 

I have tried add the code:

<video width="640" height="360" data-form-id="1" data-gate-time="15">
    <source type="video/youtube" src="https://www.youtube.com/watch?v=QT6169rdMdk" />
</video>

Effect is the same. 

![2017-04-25_09-39-08](https://cloud.githubusercontent.com/assets/25117928/25373802/4fe11ae8-299b-11e7-9ad9-ab0f982cceaf.jpg)
![2017-04-25_09-40-01](https://cloud.githubusercontent.com/assets/25117928/25373807/53fff5a4-299b-11e7-8a91-39009f983b87.jpg)

**Comment by shulard** [comment] 2017-05-06 15:31
Hello @Aneta09,

We'll check that issue quickly, thank you for the report !

**Comment by Aneta09** [comment] 2017-05-07 13:54
Hi @shulard,

OK :) I will wait for information.

**Comment by shulard** [comment] 2017-05-30 20:14
Hello !

I've took a look at your problem and I reproduce the bug... 

Personally I got a JavaScript error when the form is trying to be displayed...

```
TypeError: mediaPlayers[i].form is undefined[Learn More]  mtc.js:64:366
	success/< https://mautic.chstudio.fr/mtc.js:64:366
	dispatchEvent https://mautic.chstudio.fr/mtc.js:44:11821
	createEvent https://mautic.chstudio.fr/mtc.js:44:24801
	onReady/< https://mautic.chstudio.fr/mtc.js:44:24216
```

Have you something like this on your side ?

I'm going to create an issue on the mautic/mautic repository. I think on the plugin side there is no problems, the shortcode is interpreted, the video is loaded and the form is displayed (at least it try to).

**Comment by shulard** [comment] 2017-05-30 20:21
The issue on mautic repository: mautic/mautic/issues/4174

**Comment by Aneta09** [comment] 2017-05-31 06:25
The shortcode now is working. My code is:

<video width="780" height="460" data-form-id="11" data-gate-time="27">
<source type="video/youtube" src="https://youtu.be/XDL0x8qMsx0" />
</video>

You can check here: https://www.mymautic.pl/role-uzytkownicy-mautic/

What I have changed:
1. updated Mautic to 2.8.1
2.  added this code in Wordpress & Mautic htaccess files:

</ifModule>

<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$">
    Header set Access-Control-Allow-Origin "*"

  </FilesMatch>
</IfModule>

When the problem with Origin Access was missed the video game started work. Could you check it works too in your test?

**Comment by shulard** [comment] 2017-05-31 08:11
Hello !

Thank you for the quick reply !
You found it, it was only related to CORS settings... 

I've open a discussion about JavaScript user friendly message on slack : https://mautic.slack.com/archives/C02HV76BW/p1496217938974439

However, using the `Access-Control-Allow-Origin` header is not the cleanest solution here because you authorize anyone on the web to make request to your Mautic instance.
There is a section in the configuration panel named "CORS Settings" (https://youmauticurl/s/config/edit) and you can whitelist the domains which are able to perform the requests.

In you case you need to add : https://www.mymautic.pl

I think it's a cleaner way which easier and allow more control and security.

I close the issue here since it's resolved :)

**Closed by shulard** 2017-05-31 08:11 UTC
Labels: bug

**Comment by Aneta09** [comment] 2017-05-31 12:14
Nice :) I had had the CORS setting like you wrote. Please tell me can I add two different websites, and integrated one Mautic installation whit two different websites. Do you have any experience in this kind of use?

**Comment by shulard** [comment] 2017-05-31 12:20
Of course you can do that, in this CORS setting you can add multiple URLs (just one per line).

As an example on my installation :

```
https://chstudio.fr
http://wordpress.dev:8000
```

Also to keep tracking visitors, you can make reports filters on the `Hit url` criteria like this :

<img width="861" alt="screen shot 2017-05-31 at 14 16 45" src="https://cloud.githubusercontent.com/assets/482993/26631625/4203dae0-460c-11e7-9a66-664b0e492265.png">

Like that you can track 2 websites but still have the metrics per website when needed !

**Comment by ThomasNorden** [comment] 2018-06-26 11:02
I am getting the same error, using Wordpress. I don't have access to any htaccess file. Shouldn't this work after I've installed the Mautic Wordpress plugin?

**Comment by ThomasNorden** [comment] 2018-06-26 11:06
I added https://www.mymautic.pl in my CORS settings, but I still get "undefined"
